### PR TITLE
update mesos to 0.26.0

### PR DESCRIPTION
**Pull request by sander6**
Includes some commits that were never merged in but were used to build the existing container.

### CODE REVIEW

**Comment by JamesAwesome** [comment]
LGTM

**Comment by davidsayers** [comment]
To me it looks like dockerhub is building from the spark-mesos-hadoop branch. Can you check if thats correct? This may then need merged into it instead of master.

**Comment by pguelpa** [comment]
:+1: 

I think @davidsayers is correct that it's looking at a different branch. This incorporates the majority of changes in that branch, it looks like @akatz and I didn't do a good job of cleaning that up while we were hacking it together.

@sander6 brought up the good point of needing a way to version these things, ideally with tags now that the Dockerhub allows it. Do we think it's worthwhile to start breaking these Dockerfiles into separate repos? Or would tagging with prefix like `spark-0.0.1` be good enough for now?

**Comment by davidsayers** [comment]
:+1: for tagging
:+1: Dockerfile LGTM

**Comment by sander6** [comment]
@davidsayers This branch is based of that `spark-mesos-hadoop` branch.

**Comment by davidsayers** [comment]
i don't mind where the Dockerfile goes. Either update Dockerhub to build from master or merge this into the spark-mesos-hadoop branch.

**Comment by sander6** [comment]
@pguelpa @davidsayers We'll probably have to coordinate the deploy of this with the update to Mesos so there's no downtime.

**Comment by davidsayers** [comment]
agreed, we can discuss a time for production once we are happy that this fixes the issue.

**Pull request merged**
