### PR TITLE
WIP: Iniital attempt at a ShopKeep base spark image

### PR DESCRIPTION
**Pull request by pguelpa**

### CODE REVIEW

**Comment by paddycarey** [comment]
@pguelpa can this be closed?

**Comment by akatz** [comment]
I don't think so. The one in master is very naive.

**Comment by pguelpa** [comment]
@akatz - are we using the build from the branch? Or what are we using currently? To be honest I'd completely forgotten about this PR.

**Comment by akatz** [comment]
I think we are using a build of this that is out in the wild off of a branch that was manually pushed. I will Fix this up.

**Comment by pguelpa** [comment]
:heart:

**Pull request closed without merging**
